footprint: [[-0.20, -0.20], [-0.20, 0.20], [0.20, 0.20], [0.20, -0.20]]
footprint_padding: 0.02

robot_base_frame: base_link
update_frequency: 2
publish_frequency: 1
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}

range_sensor_layer:
  clear_threshold:    0.20
  mark_threshold:     0.80
  inflate_cone:  0.0
  clear_on_max_reading: true
  topics: ["/rangeSonar_c","/rangeSonar_l","/rangeSonar_r","/rangeSonar_s_l","/rangeSonar_s_r"]

inflation_g:
    inflation_radius: 0.8
    
inflation_l:
    inflation_radius: 0.10




