global_frame: map
rolling_window: false
track_unknown_space: true

plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: inflation_g,               type: "costmap_2d::InflationLayer"}
  - {name: range_sensor_layer,           type: "range_sensor_layer::RangeSensorLayer"}
