global_frame: odom
rolling_window: true
#width: 1.5
#height: 1.5
width: 8.0
height: 8.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_l,                 type: "costmap_2d::InflationLayer"}
  - {name: range_sensor_layer,           type: "range_sensor_layer::RangeSensorLayer"}
